#指定服务注册中心的地址
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
      #服务的端口
server:
  port: 8769
#服务名
spring:
  application:
    name: service-zuul
#以/api-a/ 开头的请求都转发给service-ribbon服务
#以/api-b/开头的请求都转发给service-feign服务
zuul:
  routes:
    api-a:
      path: /api-a/**
      serviceId: customer
    api-b:
      path: /api-b/**
      serviceId: service-feign